# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Category.destroy_all
Attraction.destroy_all

ride = Category.create(name: "ride")
dining = Category.create(name: "dining")
show = Category.create(name: "show")
photoop = Category.create(name: "photoop")
shopping = Category.create(name: "shopping")


Attraction.create(name: "Alien Pizza Planet", category: dining )
Attraction.create(name: "Bengal BBQ", category: dining )
Attraction.create(name: "Blue Bayou", category: dining )
Attraction.create(name: "Cafe Orleans", category: dining )
Attraction.create(name: "Carnation Cafe", category: dining ) 
Attraction.create(name: "Clarabelle's", category: dining )
Attraction.create(name: "Daisy's Diner", category: dining )
Attraction.create(name: "Docking Bay 7", category: dining )
Attraction.create(name: "French Market", category: dining )
Attraction.create(name: "Galactic Grill", category: dining ) 
Attraction.create(name: "Giboson Girl Ice Cream Parlor", category: dining )
Attraction.create(name: "The Golden Horseshoe", category: dining )
Attraction.create(name: "Hungry Bear", category: dining )
Attraction.create(name: "Jolly Holiday Bakery", category: dining )
Attraction.create(name: "Market House", category: dining )
Attraction.create(name: "Oga's Cantina", category: dining )
Attraction.create(name: "Plaza Inn", category: dining )
Attraction.create(name: "Pluto's Dog House", category: dining )
Attraction.create(name: "Rancho del Zocalo", category: dining )
Attraction.create(name: "River Belle Terrace", category: dining )
Attraction.create(name: "Tiki Juice Bar", category: dining )
Attraction.create(name: "The Tropical Hideaway", category: dining )
Attraction.create(name: "Troubadour Tavern", category: dining )

Attraction.create(name: "20th Century Music Company", category: shopping )
Attraction.create(name: "Bibbidi Bobbidi Boutique", category: shopping )
Attraction.create(name: "The Briar Patch", category: shopping )
Attraction.create(name: "Candy Palace", category: shopping )
Attraction.create(name: "Creature Stall", category: shopping ) 
Attraction.create(name: "Crystal d'Orleans", category: shopping )
Attraction.create(name: "Disneyana", category: shopping )
Attraction.create(name: "Disney Showcase", category: shopping )
Attraction.create(name: "Dok-Ondar's Den of Aniquities", category: shopping )
Attraction.create(name: "Droid Depot", category: shopping ) 
Attraction.create(name: "Emporium", category: shopping )
Attraction.create(name: "Fairy Tale Treasures", category: shopping )
Attraction.create(name: "First Order Cargo", category: shopping )
Attraction.create(name: "Gag Factory", category: shopping )
Attraction.create(name: "The Mad Hater", category: shopping )
Attraction.create(name: "Pioneer Mercantile", category: shopping )
Attraction.create(name: "Pooh Corner", category: shopping )
Attraction.create(name: "Resistance Supply", category: shopping )
Attraction.create(name: "Savi's Workshop", category: shopping )
Attraction.create(name: "The Star Trader", category: shopping )
Attraction.create(name: "Toydarian Toymaker", category: shopping )
Attraction.create(name: "Westward Ho Trading Company", category: shopping )

Attraction.create(name: "Alice in Wonderland", category: ride )
Attraction.create(name: "Astro Orbitor", category: ride )
Attraction.create(name: "Autopia", category: ride )
Attraction.create(name: "Big Thunder Mountain", category: ride )
Attraction.create(name: "Buzz's Astro Blasters", category: ride ) 
Attraction.create(name: "Clasey Jr.", category: ride )
Attraction.create(name: "Davey Crockett's Canoes", category: ride )
Attraction.create(name: "Disney's Monorail", category: ride )
Attraction.create(name: "Disneyland Railroad", category: ride )
Attraction.create(name: "Great Moments with Mr. Lincoln", category: ride ) 
Attraction.create(name: "Dumbo", category: ride )
Attraction.create(name: "Finding Nemo Submarine", category: ride )
Attraction.create(name: "Gadget's Go Coaster", category: ride )
Attraction.create(name: "Haunted Mansion", category: ride )
Attraction.create(name: "Indiana Jones", category: ride )
Attraction.create(name: "It's a Small World", category: ride )
Attraction.create(name: "Jungle Cruise", category: ride )
Attraction.create(name: "King Authur Carrousel", category: ride )
Attraction.create(name: "Mad Tea Party", category: ride )
Attraction.create(name: "The Many Adventures of Pooh", category: ride )
Attraction.create(name: "Mark Twain Riverboat", category: ride )
Attraction.create(name: "Matterhorn Bobsleds", category: ride )
Attraction.create(name: "Millennium Falcon", category: ride )
Attraction.create(name: "Mr. Toad's Wild Ride", category: ride )
Attraction.create(name: "Peter Pan's Flight", category: ride )
Attraction.create(name: "Pinocchio's Daring Journey", category: ride )
Attraction.create(name: "Pirates of the Caribbean", category: ride )
Attraction.create(name: "Roger Rabbit", category: ride )
Attraction.create(name: "Ship Columbia", category: ride )
Attraction.create(name: "Snow White's Adventure", category: ride )
Attraction.create(name: "Space Mountain", category: ride )
Attraction.create(name: "Splash Mountain", category: ride )
Attraction.create(name: "Star Tours", category: ride )
Attraction.create(name: "Star Wars Rise of the Resistance", category: ride )
Attraction.create(name: "Storybook Canal Boats", category: ride )

Attraction.create(name: "Believe in Holiday Magic Fireworks", category: show )
Attraction.create(name: "Christmas Fantasy Parade", category: show )
Attraction.create(name: "The Dapper Dans", category: show )
Attraction.create(name: "Fantasmic", category: show )
Attraction.create(name: "Fireworks at Disneyland", category: show ) 
Attraction.create(name: "Halloween Screams Fireworks", category: show )
Attraction.create(name: "It's a Small World Holiday Lighting", category: show )
Attraction.create(name: "Magic Happens Parade", category: show )
Attraction.create(name: "Mickey and Friends Band", category: show )
Attraction.create(name: "Mickey's Mix Magic", category: show ) 
Attraction.create(name: "Royal Swing Big band", category: show )
Attraction.create(name: "Story Telling at the Royal Theater", category: show )
Attraction.create(name: "Wintertime Enchantment Castle Show", category: show )
Attraction.create(name: "Walt's Enchanced Tiki Room", category: show )

Attraction.create(name: "Disney's Castle", category: photoop )
Attraction.create(name: "Disney's Mainstreet", category: photoop )
Attraction.create(name: "Fantasy Faire Princess Encounter", category: photoop )
Attraction.create(name: "Meet Elena of Avalor", category: photoop )
Attraction.create(name: "Meet Santa", category: photoop )
Attraction.create(name: "Pixie Hollow", category: photoop )
Attraction.create(name: "Peter Pan Meet and Greet", category: photoop )
Attraction.create(name: "Star Wars Launch Bay Character Encounter", category: photoop )